package es.upm.dit.tfg.webLab.test;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;

public class TestCrearDocente {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	//Indicamos donde se encuentra el archivo con el driver de chrome
	System.setProperty( "webdriver.chrome.driver", "/home/isst/chromedriver");
	driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void CrearProfesor() {
    driver.get("http://localhost:8080/TFG/loginPage.jsp");
    driver.manage().window().setSize(new Dimension(1853, 1053));
    driver.findElement(By.id("exampleInputEmail")).click();
    driver.findElement(By.id("exampleInputEmail")).sendKeys("root@hotmail.com");
    driver.findElement(By.id("exampleInputPassword")).sendKeys("root");
    driver.findElement(By.id("exampleInputPassword")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".boton > .nav-link")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(6) span")).click();
    driver.findElement(By.name("CRUDProfesor")).click();
    driver.findElement(By.cssSelector(".border-left-primary img")).click();
    driver.findElement(By.name("nombre")).click();
    driver.findElement(By.name("nombre")).sendKeys("Pruebas");
    driver.findElement(By.name("apellidos")).sendKeys("prueba prueba");
    driver.findElement(By.name("acronimo")).sendKeys("PPP");
    driver.findElement(By.name("correo")).sendKeys("prueba@hotmail.com");
    {
      WebElement dropdown = driver.findElement(By.id("grupo"));
      dropdown.findElement(By.xpath("//option[. = 'g1']")).click();
    }
    {
      WebElement element = driver.findElement(By.id("grupo"));
      Action builder =(Action)  new Actions(driver);
      ((Actions) builder).moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("grupo"));
      Action builder =(Action)  new Actions(driver);
      ((Actions) builder).moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("grupo"));
      Action builder = (Action) new Actions(driver);
      ((Actions) builder).moveToElement(element).release().perform();
    }
    driver.findElement(By.id("grupo")).click();
    {
      WebElement dropdown = driver.findElement(By.id("dedicacion"));
      dropdown.findElement(By.xpath("//option[. = '2h']")).click();
    }
    {
      WebElement element = driver.findElement(By.id("dedicacion"));
      Action builder = (Action) new Actions(driver);
      ((Actions) builder).moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("dedicacion"));
      Action builder = (Action) new Actions(driver);
      ((Actions) builder).moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("dedicacion"));
      Action builder = (Action) new Actions(driver);
      ((Actions) builder).moveToElement(element).release().perform();
    }
    driver.findElement(By.id("dedicacion")).click();
    {
      WebElement dropdown = driver.findElement(By.id("plaza"));
      dropdown.findElement(By.xpath("//option[. = 'plaza1']")).click();
    }
    {
      WebElement element = driver.findElement(By.id("plaza"));
      Action builder = (Action) new Actions(driver);
      ((Actions) builder).moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("plaza"));
      Action builder = (Action) new Actions(driver);
      ((Actions) builder).moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("plaza"));
      Action builder =(Action)  new Actions(driver);
      ((Actions) builder).moveToElement(element).release().perform();
    }
    driver.findElement(By.id("plaza")).click();
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".btn-user")).click();
  }
}